# Default values for csi-wekafsplugin.

# -- Directory in root of file system where dynamic volumes are provisioned
dynamicProvisionPath: "csi-volumes"
# -- Name of the driver (and provisioner)
csiDriverName: "csi.weka.io"
# -- CSI driver version
csiDriverVersion: &csiDriverVersion 0.7.2

images:
  # -- CSI liveness probe sidecar image URL
  livenessprobesidecar: k8s.gcr.io/sig-storage/livenessprobe:v2.5.0
  # -- CSI attacher sidecar image URL
  attachersidecar: k8s.gcr.io/sig-storage/csi-attacher:v3.3.0
  # -- CSI provisioner sidecar image URL
  provisionersidecar: k8s.gcr.io/sig-storage/csi-provisioner:v3.0.0
  # -- CSI registrar sidercar
  registrarsidecar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.3.0
  # -- CSI provisioner sidecar image URL
  resizersidecar: k8s.gcr.io/sig-storage/csi-resizer:v1.3.0
  # -- CSI driver main image URL
  csidriver: quay.io/weka.io/csi-wekafs
  # -- CSI driver tag
  csidriverTag: *csiDriverVersion

# -- Tolerations for all CSI driver components
globalPluginTolerations: &globalPluginTolerations
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule

# -- Tolerations for CSI controller component only (by default same as global)
controllerPluginTolerations: *globalPluginTolerations

# -- Tolerations for CSI node component only (by default same as global)
nodePluginTolerations: *globalPluginTolerations

# -- Optional nodeSelector for CSI plugin deployment on certain Kubernetes nodes only
nodeSelector: {}

# -- Log level of CSI plugin
logLevel: 5

# -- for migration of pre-CSI 0.7.0 volumes only, default API secret. Must reside in same namespace as the plugin
# legacyVolumeSecretName: csi-wekafs-api-secret
