# Default values for csi-wekafsplugin.

# directory in root of file system where dynamic volumes are provisioned
dynamicProvisionPath: "csi-volumes"
# name of the driver
#  note same name will be used for provisioner name
csiDriverName: "csi.weka.io"
csiDriverVersion: &csiDriverVersion 0.7.2
# Image paths
images:
  # "images.liveness-probe-sidecar" defines the container image used for the csi liveness probe sidecar
  livenessprobesidecar: k8s.gcr.io/sig-storage/livenessprobe:v2.5.0
  # "images.attacher-sidercar" defines the container image used for the csi attacher sidecar
  attachersidecar: k8s.gcr.io/sig-storage/csi-attacher:v3.3.0
  # "images.provisioner-sidercar" defines the container image used for the csi provisioner sidecar
  provisionersidecar: k8s.gcr.io/sig-storage/csi-provisioner:v3.0.0
  # "images.registrar-sidercar" defines the container images used for the csi registrar sidercar
  registrarsidecar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.3.0
  # "images.resizer-sidercar" defines the container image used for the csi provisioner sidecar
  resizersidecar: k8s.gcr.io/sig-storage/csi-resizer:v1.3.0
  # "images.snapshotter-sidercar" defines the container image used for the csi provisioner sidecar
  snapshottersidecar: k8s.gcr.io/sig-storage/csi-snapshotter:v4.2.1
  # images.csidriver defines csidriver image used for external provisioning
  csidriver: quay.io/weka.io/csi-wekafs
  csidriverTag: *csiDriverVersion
globalPluginTolerations: &globalPluginTolerations
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule
terminationGracePeriodSeconds: 5

controllerPluginTolerations: *globalPluginTolerations
nodePluginTolerations: *globalPluginTolerations
nodeSelector: {}
logLevel: 5

# for migration of pre-CSI 0.7.0 volumes only, default API secret. Must reside in same namespace as the plugin
# legacyVolumeSecretName: csi-wekafs-api-secret
