apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storageclass-wekafs-existingpath
provisioner: wekafs.csi.k8s.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  volumeType: path/v1
  filesystemName: default
  innerPath: /my/internal/path
  allowNonExistentPath: false