apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-wekafs-fs-static
spec:
  storageClassName: storageclass-wekafs-fs-static
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  capacity:
    storage: 1Gi
  csi:
    driver: csi.weka.io
    # volumeHandle must be formatted as following:
    # dir/v1/<FILE_SYSTEM_NAME>/<INNER_PATH_IN_FILESYSTEM>
    # The path must exist, otherwise publish request will fail
    volumeHandle: fs/v1/test_filesystem
