# This file describes how to test this deployment of the CSI wekafs driver
# using the Kubernetes 1.16 E2E test suite. For details see:
# https://github.com/kubernetes/kubernetes/tree/v1.16.0/test/e2e/storage/external

StorageClass:
  FromName: true
DriverInfo:
  Name: wekafs.csi.k8s.io
  Capabilities:
    block: true
    controllerExpansion: true
    exec: true
    multipods: true
    nodeExpansion: true
    persistence: true
