kind: Pod"echo", "HELLO WORLD", ">", "/data/hello.txt", ";",
apiVersion: v1
metadata:
  name: my-csi-app-inline
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.wekafs.csi/node
            operator: Exists
  containers:
    - name: my-frontend
      image: busybox
      volumeMounts:
      - mountPath: "/data"
        name: my-csi-volume
      command: [ "echo", "HELLO WORLD", ">", "/data/hello.txt", ";", "sleep", "1000000" ]
  volumes:
    - name: my-csi-volume
      csi:
        driver: wekafs.csi.k8s.io
