kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-wekafs-test-api
spec:
  selector:
    matchLabels:
      kubernetes.io/os: linux
  template:
    metadata:
      labels:
        kubernetes.io/os: linux
    spec:
      containers:
        - name: my-frontend
          image: busybox
          volumeMounts:
          - mountPath: "/data"
            name: csi-wekafs-dir-api
          command: ["/bin/sh"]
          args: ["-c", "while true; do echo `date` hello >> /data/`hostname`.txt; sleep 10;done"]
      volumes:
        - name: csi-wekafs-dir-api
          persistentVolumeClaim:
            claimName: pvc-wekafs-dir-api # defined in pvc-wekafs-dir.yaml
