apiVersion: v1
kind: Secret
metadata:
  name: csi-wekafs-api-secret
  namespace: csi-wekafs
type: Opaque
data:
  username: YWRtaW4=
  password: MTIzNDU2
  organization: Um9vdA==
  endpoints: aHR0cDovL2t3dXN0ZXItMC53ZWthbGFiLmlvOjE0MDAwLGh0dHA6Ly9rd3VzdGVyLTEud2VrYWxhYi5pbzoxNDAwMA==


  # You can include additional key value pairs as you do with Opaque Secrets
