apiVersion: v1
kind: Secret
metadata:
  name: csi-wekafs-api-secret
  namespace: csi-wekafs
type: Opaque
data:
  # username to connect to the cluster API (base64-encoded)
  username: YWRtaW4=
  # password to connect to the cluster API (base64-encoded)
  password: YWRtaW4=
  # organization to connect to (default Root, base64-encoded)
  organization: Um9vdA==
  endpoints: MTcyLjMxLjEzLjY3OjE0MDAwLDE3Mi4zMS4xNS41MzoxNDAwMCwxNzIuMzEuNi41NzoxNDAwMCwxNzIuMzEuMy4xOjE0MDAwLDE3Mi4zMS4xMS40NjoxNDAwMCwxNzIuMzEuOS4yNDA6MTQwMDAK
  # protocol to use for API connection (may be either http or https, base64-encoded)
  scheme: aHR0cA==
