apiVersion: v1
kind: Secret
metadata:
  name: secret-api-valid
  namespace: csi-wekafs
type: Opaque
data:
  # username to connect to the cluster API (base64-encoded)
  username: YWRtaW4=
  # password to connect to the cluster API (base64-encoded)
  password: YWRtaW4=
  # organization to connect to (default Root, base64-encoded)
  organization: Um9vdA==
  endpoints: MTcyLjMxLjEzLjg1OjE0MDAwLDE3Mi4zMS4xMC4xODc6MTQwMDAsMTcyLjMxLjUuMTkyOjE0MDAwLDE3Mi4zMS44LjIyNDoxNDAwMCwxNzIuMzEuNS4xNTc6MTQwMDAsMTcyLjMxLjYuNjM6MTQwMDA=

  # protocol to use for API connection (may be either http or https, base64-encoded)
  scheme: aHR0cA==
