kind: Pod
apiVersion: v1
metadata:
  name: app-api-old-csi-no-secret
spec:
  # make sure that pod is scheduled only on node having weka CSI node running
  nodeSelector:
    topology.csi.weka.io/global: "true"
  containers:
    - name: my-frontend
      image: ubuntu
      volumeMounts:
      - mountPath: "/data"
        name: my-csi-volume
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo `date` hello >> /data/temp.txt; sleep 10;done"]
  volumes:
    - name: my-csi-volume
      persistentVolumeClaim:
        claimName: pvc-api-old-csi-no-secret # defined in pvc-wekafs-dir-api.yaml
