apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storageclass-api-old-csi-no-secret
provisioner: csi.weka.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  volumeType: dir/v1
  filesystemName: default
