apiVersion: v1
kind: Secret
metadata:
  name: secret-api-new-csi-old-cluster
  namespace: csi-wekafs
type: Opaque
data:
  # username to connect to the cluster API (base64-encoded)
  username: YWRtaW4=
  # password to connect to the cluster API (base64-encoded)
  password: YWRtaW4=
  # organization to connect to (default Root, base64-encoded)
  organization: Um9vdA==
  endpoints: MTcyLjMxLjQxLjU0OjE0MDAwLDE3Mi4zMS40Ny4xNTI6MTQwMDAsMTcyLjMxLjM4LjI1MDoxNDAwMCwxNzIuMzEuNDcuMTU1OjE0MDAwLDE3Mi4zMS4zMy45MToxNDAwMCwxNzIuMzEuMzguMTU1OjE0MDAwCg==
  # protocol to use for API connection (may be either http or https, base64-encoded)
  scheme: aHR0cA==
