apiVersion: v1
kind: Secret
metadata:
  name: secret-api-endpoints-with-trailing-line
  namespace: csi-wekafs
type: Opaque
data:
  # username to connect to the cluster API (base64-encoded)
  username: YWRtaW4=
  # password to connect to the cluster API (base64-encoded)
  password: YWRtaW4=
  # organization to connect to (default Root, base64-encoded)
  organization: Um9vdA==
  endpoints: CjE3Mi4zMS4xMy44NToxNDAwMCwxNzIuMzEuMTAuMTg3OjE0MDAwLDE3Mi4zMS41LjE5MjoxNDAwMCwxNzIuMzEuOC4yMjQ6MTQwMDAsMTcyLjMxLjUuMTU3OjE0MDAwLDE3Mi4zMS42LjYzOjE0MDAwCgo=
  # protocol to use for API connection (may be either http or https, base64-encoded)
  scheme: aHR0cA==
